### ISSUE TITLE
Possible SQLInjection vulnerability

### ISSUE THREAD

**Issue by arkoc** [nulledcc/speedme#1]
Possible SQL Injection vulnerability in https://github.com/nulledcc/speedme/blob/master/api/library/db.php

Parameter `$table_name`.
```
        public static function table_exist($table_name = ''){
            self::connect();
            try {
                if(self::$pdo->query("SELECT 1 FROM {$table_name} LIMIT 1")){
                    return true;
                }
            }catch (\PDOException $e) {
                return FALSE;
            }
            return false;
        }
```

**Comment by nulledcc** [comment]
Dear @arkoc as 'table_exist' query may  vary because of developer needs and before it acts it need to be filtered before calling this method. I added alternative way for it. if you have suggestion please let me know.
